### ISSUE TITLE
Transpilation error - sample requested

### ISSUE THREAD

**Issue by marcelinhov2** [nathanagez/serverless-typeorm-migrations#8] opened 2021-04-22 16:38 UTC
Hey man,

Can you provide a Hello World sample for this currently working? I'm having a lot of troubles, because typeorm generates .ts files and it's not running in lambda for me. Also it looks like the migrations files is not going to the build folder.

THanks.

**Comment by marcelinhov2** [comment] 2021-04-22 16:39
And this is the error I'm getting in AWS
![image](https://user-images.githubusercontent.com/232648/115752132-31acb980-a370-11eb-8134-db2cf4ff9eb7.png)

I don't know what do to anymore 🤣 .

Thanks.

**Comment by nathanagez** [comment] 2021-04-22 16:52
Hi @marcelinhov2 ,

You can't run typescript file directly on lambda, you must have to transpile your files to JavaScript ones like I mentioned [here](https://github.com/nathanagez/serverless-typeorm-migrations#nestjs-example)

> Next you have to transpile .ts migration files to .js to make it work before deploying or invoking functions

**Comment by marcelinhov2** [comment] 2021-04-22 17:02
Hey @nathanagez, thanks for your quick reply.

It would be nice to have this feature out of the box. I mean, I already tried to transpile here but I'm having a huge amount of problems. It's already my 2nd day trying to run this :(

**Comment by marcelinhov2** [comment] 2021-04-22 17:04
If you have any repository with a working sample, I would appreciate a lot 🙏

**Comment by marcelinhov2** [comment] 2021-04-22 17:16
I tried with webpack, for example, but it only builds the migration.ts file. For the files inside src (migration and entity folder) it doesn't compiles.

**Comment by nathanagez** [comment] 2021-04-22 17:21
> Hey @nathanagez, thanks for your quick reply.
> 
> It would be nice to have this feature out of the box. I mean, I already tried to transpile here but I'm having a huge amount of problems. It's already my 2nd day trying to run this :(

Can you describe in more details what are you problems, what do you mean by a huge amount of problems ? 
We can probably run a script that will do the transpilation for you but I don't have time to work on it, feel free to open a PR if you have time ! :)
And keep in mind that this script will run the same command that are in the `package.json`:

Even if I create an example repository you will have the same content has the README.md file, it is a copy/paste of a basic `serverless.yml` file.




> I tried with webpack, for example, but it only builds the migration.ts file. For the files inside src (migration and entity folder) it doesn't compiles.

If I understand correctly, this is more a problem with your transpiler configuration than with the plugin itself. What is your `tsconfig.json` file configuration ?

**Comment by nathanagez** [comment] 2021-04-22 17:23
First of all, are you using a Framework with this ? What is the architecture of your project, give us more information to reproduce your errors.

**Comment by nathanagez** [comment] 2021-04-22 17:37
Just tested it with a Postgres Database.

Here is my `ormconfig.js`

```js
module.exports = {
  type: 'postgres',
  host: process.env.POSTGRES_HOST,
  port: parseInt(process.env.POSTGRES_PORT),
  username: process.env.POSTGRES_USER,
  password: process.env.POSTGRES_PASSWORD,
  database: process.env.POSTGRES_DB,
  entities: ['src/shared/entities/*.ts'],
  migrations: ['src/migration/**/*.ts'],
  subscribers: ['src/subscriber/**/*.ts'],
  seeds: ['typeorm/seeds/**/*{.ts,.js}'],
  factories: ['typeorm/factories/**/*{.ts,.js}'],
  cli: {
    entitiesDir: 'src/shared/entities/',
    migrationsDir: 'src/migration',
    subscribersDir: 'src/subscriber',
  },
};
```

After that I ran (you must look at the `README.md` for the command details): 

1. `npm run migration:generate test`
2.  `npm run migration:up`

![Screenshot 2021-04-22 at 19 36 36](https://user-images.githubusercontent.com/7148684/115760940-122e8480-a3a2-11eb-9f00-e2ff4da05e61.png)

**Comment by nathanagez** [comment] 2021-04-22 17:41
> Hey @nathanagez, thanks for your quick reply.
> 
> It would be nice to have this feature out of the box. I mean, I already tried to transpile here but I'm having a huge amount of problems. It's already my 2nd day trying to run this :(

Can you describe in more details what are your problems, what do you mean by a huge amount of problems ? 

This is not the job of the plugin to transpile the files for you, as a matter of principle your migrations should [already be ready and generated](https://github.com/typeorm/typeorm/blob/master/docs/migrations.md), this plugin will only run them on a lambda.

Even if I create an example repository you will have the same content has the README.md file, it is a copy/paste of a basic `serverless.yml` file.

> I tried with webpack, for example, but it only builds the migration.ts file. For the files inside src (migration and entity folder) it doesn't compiles.

Since it is not a problem related with the plugin but with your transpiler configuration, I will close this issue.

**Closed as completed by nathanagez** 2021-04-22 17:41 UTC
Labels: help wanted, question

**Comment by marcelinhov2** [comment] 2021-04-22 19:52
Hey man, sorry for the delay. I started from beggining again, I already transpiled my sample migration.

I defined the env vars here:
![image](https://user-images.githubusercontent.com/232648/115776327-5f066100-a38a-11eb-8ed5-bb105a45fa4a.png)

But I'm getting this error right here (Serverless Migrations - SLS_TYPEORM_MIGRATIONS_DATABASE_URL environment variable required):
<img width="1099" alt="image" src="https://user-images.githubusercontent.com/232648/115776423-780f1200-a38a-11eb-9159-feb7690477a8.png">

Files:
![image](https://user-images.githubusercontent.com/232648/115776557-a391fc80-a38a-11eb-9c38-90ff42394b73.png)

![image](https://user-images.githubusercontent.com/232648/115776733-d2a86e00-a38a-11eb-848b-4f9d00f3eb15.png)

What do you think I can be missing here? 

Thank you so much for your help.

**Comment by marcelinhov2** [comment] 2021-04-22 20:06
https://forum.serverless.com/t/new-version-2-36-0-breaks-deploy-when-org-is-set/14791

```
serverless --version
Framework Core: 2.37.1
Plugin: 4.5.3
SDK: 4.2.2
Components: 3.9.0
```

**Comment by marcelinhov2** [comment] 2021-04-22 20:11
what's the serverless framework version you are using @nathanagez? 

Thanks.

**Comment by marcelinhov2** [comment] 2021-04-23 13:18
Hey @nathanagez after a few more hours I realized that for some reason, the environment variables defined over the serverless.yml file are not reaching your code when I run `npm run migration:up`. I had forced the values over your compiled code and the migration worked. Do you have any ideia why it could be happening? 

Thanks.

**Comment by marcelinhov2** [comment] 2021-04-23 13:22
FOUND IT, you have a typo in your docs:

SLS_TYPEORM_MIGRATION_FOLDER should be SLS_TYPEORM_MIGRATION**S**_FOLDER in the `serverless.yml` file.

**Comment by marcelinhov2** [comment] 2021-04-23 13:27
![image](https://user-images.githubusercontent.com/232648/115878005-6ecf8500-a41e-11eb-85b5-c83def07a0a6.png)
and a terrible error message for this by the way...

**Comment by marcelinhov2** [comment] 2021-04-23 13:39
now it's all working as expected.

Thanks.

**Comment by marcelinhov2** [comment] 2021-04-23 15:26
also, if you add the param `-o` to your generate and create cli calls, you will already generate the files in .js which helps a lot.

**Comment by nathanagez** [comment] 2021-04-27 12:25
@marcelinhov2 thank you for your feedback, sorry I was very busy I did not had time to answer your last questions but it seems that you resolved it! 

Great news, hope the plugin will help you!

**Comment by marcelinhov2** [comment] 2021-05-07 13:16
@nathanagez I'm trying to find a way to integrate the generate step in a CI/CD tool and doesn't find much about this. I'm here to ask if you already needed to build something similar. 

Thanks my friend.
